<?php

/**************************
 * ACF FIELD E-MAIL INSTELLINGEN
 **************************/
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5f6a7d91d4419',
	'title' => 'Reservatie e-mail instellingen',
	'fields' => array(
		array(
			'key' => 'field_5f6a7e321330f',
			'label' => 'Reservatie goedgekeurd - tekst',
			'name' => 'reservatie_goedgekeurd',
			'type' => 'textarea',
			'instructions' => 'Je kan hier de e-mail tekst aanpassen.
							Gebruik deze TAGS:
							[NAAM]
							[EMAIL]
							[DATUM_RESERVATIE]
							[UUR_RESERVATIE]
							[AANTAL_PERSONEN]
							[LUNCH_DINER]
							[TELEFOON]
							[BERICHT]',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 0,
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_5f6a86f4b21cb',
			'label' => 'Reservatie goedgekeurd - onderwerp',
			'name' => 'reservatie_goedgekeurd_onderwerp',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 0,
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5f6a7e5313310',
			'label' => 'Reservatie geannuleerd - tekst',
			'name' => 'reservatie_geannuleerd',
			'type' => 'textarea',
			'instructions' => 'Je kan hier de e-mail tekst aanpassen.
							Gebruik deze TAGS:
							[NAAM]
							[EMAIL]
							[DATUM_RESERVATIE]
							[UUR_RESERVATIE]
							[AANTAL_PERSONEN]
							[LUNCH_DINER]
							[TELEFOON]
							[BERICHT]',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 0,
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_5f6a872cb21cc',
			'label' => 'Reservatie geannuleerd- onderwerp',
			'name' => 'reservatie_geannuleerd_onderwerp',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 0,
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'opties',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5f68e011c0e98',
	'title' => 'Reservatie',
	'fields' => array(
		array(
			'key' => 'field_5f68e03e2571d',
			'label' => 'Datum reservatie',
			'name' => 'datum_reservatie',
			'type' => 'date_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 0,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_5f68e01725719',
			'label' => 'Naam',
			'name' => 'naam',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 0,
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5f68e06d2571f',
			'label' => 'Lunch of diner',
			'name' => 'lunch_of_diner',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 0,
			'choices' => array(
				'Lunch' => 'Lunch',
				'Diner' => 'Diner',
			),
			'default_value' => false,
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5f68e01c2571a',
			'label' => 'E-mail',
			'name' => 'e-mail',
			'type' => 'email',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 0,
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_5f68e0532571e',
			'label' => 'Uur reservatie',
			'name' => 'uur_reservatie',
			'type' => 'time_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 0,
			'display_format' => 'H:i:s',
			'return_format' => 'H:i:s',
		),
		array(
			'key' => 'field_5f68e0232571b',
			'label' => 'Telefoon',
			'name' => 'telefoon',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 0,
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5f68e07b25720',
			'label' => 'Aantal personen',
			'name' => 'aantal_personen',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 0,
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5f68e02a2571c',
			'label' => 'Bericht / opmerking',
			'name' => 'bericht__opmerking',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 0,
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_5f71944d9e412',
			'label' => 'Mail is verstuurd',
			'name' => 'mail_is_verstuurd',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => 'Ja',
			'ui_off_text' => 'Nee',
			'wpml_cf_preferences' => 0,
		),
		array(
			'key' => 'field_5f88af0fbe834',
			'label' => 'Bevestigd / geannuleerd',
			'name' => 'bevestigd__geannuleerd',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 0,
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => 'Reservatie is bevestigd',
			'ui_off_text' => 'Reservatie is geannuleerd',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'reservaties',
			),
		),
	),
	'menu_order' => 1,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

/**************************
 * ACF FIELD RESTAURANT GURU AWARD
 **************************/

acf_add_local_field_group(array(
	'key' => 'group_5f76cc4bd8b14',
	'title' => 'Restaurant Guru Award',
	'fields' => array(
		array(
			'key' => 'field_5f76cc57b54d9',
			'label' => 'Widget',
			'name' => 'widget_restaurant_guru',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 0,
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'opties',
			),
		),
	),
	'menu_order' => 4,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

endif;
/**************************
 * ACF FIELD TRIP ADVISOR
 **************************/
if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_5bb0ce1db4952',
		'title' => 'TripAdvisor beoordelingen',
		'fields' => array(
			array(
				'key' => 'field_593bd1c540c98',
				'label' => 'Beoordelingen',
				'name' => '',
				'type' => 'message',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'wpml_cf_preferences' => 1,
				'message' => 'Voeg hier uw beoordeling toe van Tripadvisor en kijk hoeveel bolletjes zijn aangeduid en het aantal beoordelingen. Bv: 4.5 bolletjes aangeduid van de 99 beoordelingen. Geef dit zo in 4.5/99 . Bekijk <a href="https://www.tripadvisor.be/Restaurant_Review-g801351-d3396841-Reviews-Bistro_De_Bolle-Zwevegem_West_Flanders_Province.html" target="_blank">hier uw tripadvisor beoordelingen</a>. Klik daarna op "bijwerken" in de rechterkolom.',
				'new_lines' => 'wpautop',
				'esc_html' => 0,
			),
			array(
				'key' => 'field_593bcf41ef6f7',
				'label' => 'Rating',
				'name' => 'rating',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'wpml_cf_preferences' => 1,
				'default_value' => '',
				'placeholder' => 'Geef hier uw waarde in bv: 4.8/99',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5e65f25419bcf',
				'label' => 'Widget',
				'name' => 'widget',
				'type' => 'textarea',
				'instructions' => 'Om een Tripadvisor-widget te gebruiken, voegt u de onderstaande, aangepaste code toe in het onderstaande vak',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'wpml_cf_preferences' => 1,
				'default_value' => '<div id="TA_certificateOfExcellence480" class="TA_certificateOfExcellence"><ul id="Varcqyjw" class="TA_links EDC5bIJJtIx7"><li id="cCYdpx" class="SFgK2Xgm"><a target="_blank" href="https://www.tripadvisor.be/Restaurant_Review-g801351-d3396841-Reviews-Bistro_De_Bolle-Zwevegem_West_Flanders_Province.html"><img src="https://www.tripadvisor.be/img/cdsi/img2/awards/CoE2017_WidgetAsset-14348-2.png" alt="TripAdvisor" class="widCOEImg" id="CDSWIDCOELOGO"/></a></li></ul></div><script async src="https://www.jscache.com/wejs?wtype=certificateOfExcellence&amp;uniq=480&amp;locationId=3396841&amp;lang=nl_BE&amp;year=2019&amp;display_version=2" data-loadtrk onload="this.loadtrk=true"></script>',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'new_lines' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'opties',
				),
			),
		),
		'menu_order' => 3,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));
/**************************
 * ACF FIELD ACHTERGROND FOTO
 **************************/
	acf_add_local_field_group(array(
		'key' => 'group_5e176c083bbde',
		'title' => 'Achtergrond foto',
		'fields' => array(
			array(
				'key' => 'field_5e176c1560b05',
				'label' => 'Onze kaart',
				'name' => 'onze_kaart',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '30',
					'class' => '',
					'id' => '',
				),
				'wpml_cf_preferences' => 3,
				'return_format' => 'array',
				'preview_size' => 'medium',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'field_5e176d101f149',
				'label' => 'Cadeaubon',
				'name' => 'cadeaubon',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '30',
					'class' => '',
					'id' => '',
				),
				'wpml_cf_preferences' => 3,
				'return_format' => 'array',
				'preview_size' => 'medium',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'field_5e176d1f1f14a',
				'label' => 'Impressie',
				'name' => 'impressie',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '30',
					'class' => '',
					'id' => '',
				),
				'wpml_cf_preferences' => 3,
				'return_format' => 'array',
				'preview_size' => 'medium',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'field_5e176d2a1f14b',
				'label' => 'Over ons',
				'name' => 'over_ons',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '30',
					'class' => '',
					'id' => '',
				),
				'wpml_cf_preferences' => 3,
				'return_format' => 'array',
				'preview_size' => 'medium',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'field_5e176d351f14c',
				'label' => 'Contact',
				'name' => 'contact',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '30',
					'class' => '',
					'id' => '',
				),
				'wpml_cf_preferences' => 3,
				'return_format' => 'array',
				'preview_size' => 'medium',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'field_5e176d3e1f14d',
				'label' => 'Reserveren',
				'name' => 'reserveren',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '30',
					'class' => '',
					'id' => '',
				),
				'wpml_cf_preferences' => 3,
				'return_format' => 'array',
				'preview_size' => 'medium',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'opties',
				),
			),
		),
		'menu_order' => 6,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => array(
			0 => 'permalink',
			1 => 'the_content',
			2 => 'excerpt',
			3 => 'discussion',
			4 => 'comments',
			5 => 'revisions',
			6 => 'slug',
			7 => 'author',
			8 => 'format',
			9 => 'page_attributes',
			10 => 'featured_image',
			11 => 'categories',
			12 => 'tags',
			13 => 'send-trackbacks',
		),
		'active' => true,
		'description' => '',
	));
	
	endif;