<?php

/*************************
 * ACF FIELDS TRAITEURLIJST
**************************/

if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array(
        'key' => 'group_5e860f86ec827',
        'title' => 'Traiteurlijst',
        'fields' => array(
            array(
                'key' => 'field_5e860f97ec744',
                'label' => 'Voorgerechten',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'acfe_permissions' => '',
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5e860fbaec745',
                'label' => 'Voorgerechten',
                'name' => 'voorgerechten',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'acfe_permissions' => '',
                'acfe_repeater_stylised_button' => 0,
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'table',
                'button_label' => '',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5e860fd2ec746',
                        'label' => 'Voorgerecht item',
                        'name' => 'voorgerecht_item',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'acfe_permissions' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                ),
            ),
            array(
                'key' => 'field_5e8c889fcf0ca',
                'label' => 'Hoofdgerechten',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'acfe_permissions' => '',
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5e8c88aacf0cb',
                'label' => 'Hoofdgerechten',
                'name' => 'hoofdgerechten',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'acfe_permissions' => '',
                'acfe_repeater_stylised_button' => 0,
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'table',
                'button_label' => '',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5e8c88aacf0cc',
                        'label' => 'Hoofdgerecht item',
                        'name' => 'hoofdgerecht_item',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'acfe_permissions' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                ),
            ),
            array(
                'key' => 'field_5f93ff7325dab',
                'label' => 'Opties',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'wpml_cf_preferences' => 0,
                'placement' => 'top',
                'endpoint' => 1,
            ),
            array(
                'key' => 'field_5ec9266a79ca7',
                'label' => 'Traiteur bestellingen',
                'name' => 'traiteur_bestellingen',
                'type' => 'true_false',
                'instructions' => 'Zet het bestelformulier actief / niet actief.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => 'Actief',
                'ui_off_text' => 'Niet actief',
                'wpml_cf_preferences' => 1,
            ),
            array(
                'key' => 'field_5f940089c5245',
                'label' => 'Datum traiteur bestellingen',
                'name' => 'datum_traiteur_bestellingen',
                'type' => 'repeater',
                'instructions' => 'Datum en tijdstip afhalingen traiteurbestellingen',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'wpml_cf_preferences' => 0,
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'table',
                'button_label' => 'Nieuwe datum',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5f940fc0cefcf',
                        'label' => 'Datum',
                        'name' => 'datum',
                        'type' => 'date_picker',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '25',
                            'class' => '',
                            'id' => '',
                        ),
                        'wpml_cf_preferences' => 0,
                        'display_format' => 'd/m/Y',
                        'return_format' => 'd/m/Y',
                        'first_day' => 1,
                    ),
                    array(
                        'key' => 'field_5f94105b92a3c',
                        'label' => 'Uur afhalen vanaf',
                        'name' => 'uur_afhalen_vanaf',
                        'type' => 'time_picker',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '25',
                            'class' => '',
                            'id' => '',
                        ),
                        'wpml_cf_preferences' => 0,
                        'display_format' => 'H:i',
                        'return_format' => 'H:i',
                    ),
                    array(
                        'key' => 'field_5f94108d92a3d',
                        'label' => 'Uur afhalen tot',
                        'name' => 'uur_afhalen_tot',
                        'type' => 'time_picker',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '25',
                            'class' => '',
                            'id' => '',
                        ),
                        'wpml_cf_preferences' => 0,
                        'display_format' => 'H:i',
                        'return_format' => 'H:i',
                    ),
                    array(
                        'key' => 'field_5f94112a0712a',
                        'label' => 'Interval tijdstip (minuten)',
                        'name' => 'interval_tijdstip',
                        'type' => 'select',
                        'instructions' => 'Geef aan wat de tijdsinterval is tussen "uur afhalen vanaf" tot en met "uur afhalen tot"',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'wpml_cf_preferences' => 0,
                        'choices' => array(
                            15 => '15',
                            30 => '30',
                            45 => '45',
                            60 => '60',
                        ),
                        'default_value' => false,
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 0,
                        'return_format' => 'value',
                        'ajax' => 0,
                        'placeholder' => '',
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'bestellijst',
                ),
            ),
        ),
        'menu_order' => 2,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'left',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));
    
    endif;