---
deployment:
  tasks:
    - export DEPLOYPATH=/home/bistrodebolle/staging.bistrodebolle.be/wp-content/themes/bistrodebolle-child
    - /bin/rm -Rf $DEPLOYPATH
    - /bin/mkdir $DEPLOYPATH
    - /bin/cp -R * $DEPLOYPATH
    